### PR TITLE
Added example for setting default values for function arguments

### PR DESCRIPTION
**Pull request by infernocloud**

### CODE REVIEW

**Comment by ryanguill** [comment]
I think this is a good idea, but you should leave `required` off of that no? a default value with a required argument doesn't make sense.

**Comment by abramadams** [comment]
I second that @ryanguill, using ```required``` with a default value should not be advocated

**Comment by adamcameron** [comment]
Thirded.

**Comment by infernocloud** [comment]
Updated this PR without the required keyword

**Comment by adamcameron** [comment]
Cheers!

**Pull request merged**
